---
title: "Project Group 8"
author: Utkuhan Genc, Cole Parsons, Amanda Crowe, Collin Jewett, Kayla Parker, Michael
  Campbell, Shriya Das
date: "November 5, 2018"
output: html_document
---

```{r setup, eval  = FALSE}
install.packages("zipcode")
install.packages("generator")
install.packages("RMySQL")
install.packages("random")
install.packages("tidyr")
install.packages("sampling")
install.packages("ggmap")
install.packages("rvest")
install.packages("RMySQL")
install.packages("httr")
install.packages("XML")
install.packages("stringi")
install.packages("tidyverse")
install.packages("geosphere")
```

```{r}
library(tidyverse) 
library(generator)
library(zipcode)
library(tidyr)
library(dplyr)
library(sampling)
library(ggmap)
library(rvest)
library(stringr)  
library(ggplot2)
library(stringi)
library(RMySQL)
library(geosphere)
```

```{r}
con <- dbConnect(MySQL(),
         user="g1090429", password="WhereHouse?",
         dbname="g1090429", host="mydb.ics.purdue.edu")
on.exit(dbDisconnect(con))
```

```{r}
all_cons <- dbListConnections(MySQL())
for (con in all_cons)
dbDisconnect(con)
```

```{r user}
#USER DATATABLE
sample_size <- lesse_num + nrow(owner)


#First and Last Names
full_name <- r_full_names(sample_size)
df <- as.data.frame(full_name)
names <- tidyr::separate(df, full_name, sep = " ", c("First_name", "Last_name" ))

#User type
user_type <- as.data.frame(rbinom(sample_size, 1, nrow(owner)/ sample_size))
sum(user_type) - length(user_type)

#Phone Number
Phone_num <- r_phone_numbers(sample_size)
Phone_num <- as.data.frame(Phone_num)

#Email
Email <- r_email_addresses(sample_size)
Email <- as.data.frame(Email)

#Date of Birth 
DOB <- sample(seq(as.Date('1950/01/01'), as.Date('2000/01/01'), by="day"), sample_size, replace = TRUE )
DOB <- as.data.frame(DOB)



#Address
data <- read.csv("address.csv")
data <- as.data.frame(data)
address_2 <- 0

#Password
password<- stri_rand_strings(n=sample_size, length=15, pattern="[A-Za-z0-9]")
password <- as.data.frame(password)

a <- data.frame(DOB,Phone_num, user_type, Email, password)



user <- names
user$first_name <- as.character(names$First_name)
user$last_name <- as.character(names$Last_name)
user$address_1 <- data$Street.Address
user$address_2 <- address_2
user$city <- as.character(data$City)
user$state <- as.character(data$State)
user$zipcode <- as.integer(data$Zip.Code)
user$dob <- a$DOB
user$phone_num <- a$Phone_num
user$email <- as.character(a$Email)
user$password <- as.character(a$password)
user <- user[, -c(1:2)]
user <- tibble::rowid_to_column(user, "id")

data(zipcode)

user1 <- user
colnames(user1)[8] <- "zip" 
user1$zip <- as.numeric(user1$zip)


zipcode$zip <- as.numeric(zipcode$zip)
user1 <- left_join(user1, zipcode, by= "zip")


dbWriteTable(con, "User", user, overwrite = TRUE)

```

```{r foreign keys}
owner_id <- user[sample(nrow(user), 399), 1]
user[owner_id,1]
lessee_id <- user[-owner_id,1]
```

```{r owner}

#Company Name 
company_names <- lapply(paste0('http://www.hoovers.com/company-information/company-search.html?term=warehousing-and-storage--&nvcnt=76&maxitems=100&page=', 1:10,sep="/"),
                function(url){
                  url %>% read_html() %>% 
                    html_nodes(".company_name") %>% 
                    html_text() %>%
                    str_trim() 
                })
company_names <- unlist(company_names)
company_names<- as.data.frame(company_names)
owner <- company_names
colnames(owner)[1] <- "Company_name"

#Bank Account Number 
bank_account <- sample(10000000000:999999999999, nrow(company_names),replace=TRUE)
bank_account <- as.data.frame(bank_account)

#Routing Number
routing_number <- sample(1e9:1e10,nrow(company_names),replace=TRUE)
routing_number <- as.data.frame(routing_number)


a <- bind_cols(bank_account,routing_number)
owner$bank_acc <- a$bank_account
owner$routing_num <- a$routing_number

specific <- sample(1:1000,3)
owner <- owner[sample(nrow(owner),399),]

owner$owner_id <- owner_id 
owner <- owner[c(4,1,2,3)]

dbWriteTable(con, "Owner", owner, overwrite = TRUE)

```

```{r lessee}
lesse_num <- nrow(owner) * 100
credit_card_num <- r_credit_card_numbers(lesse_num)
credit_card_num <- gsub("-","", credit_card_num)
credit_card_num <- as.data.frame(credit_card_num)

expiration_month <- sample(1:12,lesse_num, replace = TRUE)
expiration_year <- sample(2018:2050, lesse_num, replace = TRUE)
expiration <- data.frame(expiration_month, expiration_year)
cvc <- sample(100:999, lesse_num, replace = TRUE)
cvc <- as.data.frame(CVC)

lessee_id <- as.data.frame(lessee_id)
lessee <- bind_cols(lessee_id,credit_card_num,expiration, CVC)

dbWriteTable(con, "Lessee", lessee, overwrite = TRUE)

```

```{r warehouse}
Street <- lapply(paste0("https://www.loopnet.com/warehouses-for-lease/", 1:20,sep="/"),
                function(url){
                  url %>% read_html() %>% 
                    html_nodes(".listingTitle") %>% 
                    html_text() %>%
                    str_trim() %>%
                    gsub('-* Warehouse for Lease', '', .)
                  
              })

Street <- unlist(Street)
Street <- as.data.frame(Street)


#City and State 
city_state <- lapply(paste0('https://www.loopnet.com/warehouses-for-lease/', 1:20,sep="/"),
                 function(url){
                   url %>% read_html() %>% 
                     html_nodes(".listingDescription b") %>% 
                     html_text() %>%
                     str_trim()
                   
                 })

city_state <- unlist(city_state)
city_state <- as.data.frame(city_state)
city_state <- city_state %>% separate(city_state, sep = "," ,c("city","State"))

#Zipcodes


#Attributes 
df1 <- lapply(paste0('https://www.loopnet.com/warehouses-for-lease/', 1:20,sep="/"),
                     function(url){
                       url %>% read_html() %>% 
                         html_nodes(".listingAttributes tr") %>% 
                         html_text() %>%
                         str_trim()
                     })

df1 <- unlist(df1)
df1 <- as.data.frame(df1)

#Price per skid per month 
price <- df1 %>% filter(str_detect(df1,"Price:")) %>%
  separate(df1, sep = ":", c("Text","Fee")) %>%
  separate(Fee, sep = "-", c("Fee", "Max"))

price$Text <- NULL
price$Max <- NULL

price$Fee <- gsub("[^0-9\\.]", "", price$Fee)
price <- as.numeric(price$Fee) 
price <- as.data.frame(price)

#Building Size 
building_size <- df1 %>% filter(str_detect(df1, "Building Size")) %>%
  separate(df1, sep = ":", c("Text", "Size"))
building_size$Text <- NULL
building_size$Size <- gsub("[^0-9\\]", "", building_size$Size) 
Size <- as.numeric(building_size$Size)
Size <- as.data.frame(Size)

#Temperature control 
temp <- c("dry", "climate_controlled", "cooler", "frozen")

#Capacity
capacity <- floor(capacity_find(warehouse$Size))

#Warehouse data frame 

warehouse <- data.frame(Street,city_state,price, Size) 
warehouse <- as.data.frame(warehouse) %>%
  mutate(price = price * 12) %>% 
  mutate(price, replace(price, price > 30, NA)) %>%
  na.omit
warehouse$`replace(price, price > 30, NA)` <- NULL



warehouse <- read.csv("test.csv")

warehouse$X <- NULL



warehouse <- tibble::rowid_to_column(warehouse, "ID")
warehouse <- left_join(warehouse, zipcodes, by = "ID")

warehouse <- warehouse %>% na.omit
warehouse$temp <- sample(temp, nrow(warehouse), replace = TRUE, prob = c(.32,.54,.09,.05))


warehouse$capacity <- capacity
warehouse$lowest_temp[warehouse$temp == "frozen"] <- 0
warehouse$lowest_temp[warehouse$temp == "cooler"] <- 34
warehouse$lowest_temp[warehouse$temp == "climate_controlled"] <- 55
warehouse$lowest_temp[warehouse$temp == "dry"] <- 75
warehouse$highest_temp <- 75 
warehouse$price_per_skid <- warehouse$Price *16 / 365
warehouse$adress_2 <- 0
warehouse$adress_1 <- warehouse$Street
warehouse$Price <- NULL

warehouse <- warehouse[c(1,13,12,3,4,5,11,8,6,7,9,10)]
warehouse <- as.data.frame(warehouse)
owner_warehouse <- sample(owner$owner_id,nrow(warehouse),1)
warehouse$owner_id <- owner_warehouse

colnames(warehouse) <- c("warehouse_id", "address_1", "address_2", "city", "state", "zipcode", "price_per_skid", "capacity","size" , "storage_pref", "lowest_temp", "highest_temp","owner_id" )

warehouse$temp <- NULL

warehouse1 <- warehouse
colnames(warehouse1)[6] <- "zip"


warehouse1 <- left_join(warehouse1, zipcode, by = "zip")

head(warehouse)
dbWriteTable(con, "Warehouse", warehouse, overwrite = TRUE)


```

```{r contract}
selected_id <- matrix()
lessee_pref <- matrix()
selected_user <- user1[FALSE,]
distance <- warehouse1[FALSE,]
warehouses <- warehouse[FALSE,]
contract_final <- data.frame()

contract <-NULL


for(i in 1:nrow(lessee)){
  selected_id<- sample(lessee$lessee_id, 1, 1)
  selected_id <- as.vector(selected_id)
  selected_user <- user1[selected_id, ]
  distance <- mapply(calc_dist, warehouse1$longitude, warehouse1$latitude)
  distance <- distance * 0.000621371
  warehouses <- warehouse[which(distance < 500),]
  
  start_date <- sample(seq(as.Date('2018/01/01'), as.Date('2018/12/30'), by="day"), 1)
  repeat{
    end_date <- sample(seq(as.Date('2018/01/02'), as.Date('2018/12/31'), by="day"), 1)
    if (end_date > start_date){
      break
    }
  }
  diff_in_days<- as.numeric(difftime(end_date,start_date , units = c("days")))
  repeat {
    num_skids <- rnorm(1,100,30)
    num_skids <- num_skids - (num_skids %% 1)
    if (num_skids > 0){
      break
    }
    return(num_skids)
  }
  
  selected_warehouse <- warehouses[sample(nrow(warehouses),1),]
  total_price <- as.numeric(num_skids * selected_warehouse[,7] * diff_in_days) 
  deposit <- total_price * 0.1
  
  selected_owner <- owner[which(owner_id == selected_warehouse$owner_id),1:2]

  selected_owner$owner_first_name <- user[selected_owner[1,1],2]
  selected_owner$owner_last_name <- user[selected_owner[1,1],3]
  selected_lessee <- lessee[which(lessee_id == selected_id),1]
  selected_lessee <- user[selected_lessee,1:3]
 
  contract  <- data.frame(selected_lessee,selected_owner[,c(1,3,4)],selected_warehouse[,1:6],start_date, end_date, num_skids, total_price, deposit)
  contract_final <- rbind(contract_final,contract)
}


```

```{r function}
#This function is for the capacity of each warehouse depending on their size. We have used a source from 

capacity_find <- function(size){
  utilization <- rnorm(1, mean = .55)
  stack_height <- sample(c(1,2,3,4))
  capacity <- size * utilization * stack_height / 16
  return(capacity)
}

calc_dist <- function(lon,lat){
  distm(c(user1[98437,]$longitude, user1[98437,]$latitude), c(lon , lat), fun = distHaversine)   
}

